CREATE DATABASE test_task CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE test_task;

CREATE TABLE data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  unique_id VARCHAR(255) NOT NULL,
  data TEXT NOT NULL
);
